title: Jake Torres â€” ePortfolio
description: Capstone ePortfolio with professional self-assessment, artifacts, and code review video.
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag

url: "https://tjake459.github.io"
baseurl: ""          
permalink: pretty    
